### ISSUE TITLE
workspaces walls isolation

### ISSUE THREAD

**Issue by maxichan** [BigE/desk-changer#13]
Can you create different wallpapers to different workspaces ?
This would be devastating XD for gnome.

How can it look :
1. Different profile for different workspace
2. Just choose different wall's from one profile, but with checking it is not repeat

**Comment by BigE** [comment]
Thank you for the great suggestion! I would really love to implement something like this as it would be very nice to have different things to look at on different desktops. Unfortunately, it would require changing how Gnome itself works and is not something my software can control. All the desk-changer daemon does, is set a gsettings key that Gnome automatically reads to display the background image. Perhaps in the future, if Gnome changes how this works, something like this might be possible. For the time being though, it is completely out of my control. Thanks again for the suggestion.

**Comment by eliotb** [comment]
This feature seems to be possible, see https://github.com/BlinkBP/walkpaper

Its code looks very simple. See
https://github.com/BlinkBP/walkpaper/blob/master/extension.js#L18

BTW It is not obvious, but in its prefs window titled "Workspace Names", you actually need to enter full paths to images to be used for wallpaper.

**Comment by eliotb** [comment]
Even simpler code: https://github.com/eliotb/walkpaper

**Comment by BigE** [comment]
This is not a direction I personally want to take the extension. As I stated before, this extension changes the image through the Python daemon. It would take a lot more work to get this working well together in the methods shown through other extensions. I am not opposed to having this functionality, but it will have to be a pull request from someone else at this time. Thanks!

**Comment by eliotb** [comment]
@BigE i guess I misunderstood what you meant by "it would require changing how Gnome itself works".

Can you give any pointer/tip on how you'd approach it.  Particularly how to split functionality between js frontend and python daemon  (so I can start off with a better chance of doing something that you'd accept)

I'm thinking that the js part of the app would connect to the 'workspace-switched' signal, and then send the new workspace index to the daemon via dbus. 
The rest would be up to the daemon would e.g. change profile per workspace
Obviously more to it than this in the gui and settings etc.

**Comment by BigE** [comment]
@eliotb My apologies, I meant that it would require changing how Gnome works for it to work with the daemon/extension as is.

As for how I would approach it... what you have described is about the same way I would do it. The only hard part I see is tracking the workspaces in the daemon itself. The daemon works based on a timer, so you would have to track each workspace individually. This would allow the timer to still control the changing of the wallpaper at a set interval and include the DBus ability to switch the wallpaper based on workspace. This is the part that could get really intricate, because then how is "history" and "queue" handled? Currently they are singular in a sense and won't handle workspaces in the way the daemon is written. You either have to write a separate history/queue for each workspace, or just assume when in "workspace" mode, your history will not be exactly what it is in normal mode. I'm definitely open to ideas on how to implement this.

I have no idea how to design the extension interface, or if any major interface changes would need to exist. I honestly haven't thought through this part of the change. I imagine that there wouldn't be anything more than a simple switch to turn on/off workspace tracking. I'm pretty open to suggestions/ideas here.
