### ISSUE TITLE
Remove desk-changer icon from top panel

### ISSUE THREAD

**Issue by sojusnik** [BigE/desk-changer#16]
Since the [desk-changer icon in the top panel](http://i.imgur.com/o8WvsJE.png) isn't really fulfilling a specific function, it would be better to remove it completely from there, if the extension is integrated in the system menu. Additionally, the icon looks a little bit out of place in terms of padding and color, since it's not monochrome, like the others.

Please consider adding a switchable option in the settings.

**Comment by BigE** [comment]
Well, the icon does serve as the preview for the extension, if that option is enabled. I would be in favor of only showing the preview there, hiding the normal icon when the preview is not selected to be shown. This would remove the icon when it servers no purpose, but still showing the preview without opening the menu just to see that.

**Comment by sojusnik** [comment]
Great idea!

**Comment by BigE** [comment]
Just updating... I believe the work is done to remedy this issue and part of the develop branch. I'm not a big user of the system integration though, so it hasn't gotten a lot of testing. If you would like to grab and install the extension from the develop branch, feel free to give me any feedback you'd like. I'm also not ready to release this yet because I want to make other changes to how the settings work. I'll be doing that work in a separate branch, so develop should remain unchanged functionality wise.

**Comment by BigE** [comment]
Closing with release of version 21 of the extension. The system icon is removed from the tray unless the preview is enabled.
