### ISSUE TITLE
Feature-request - add option to blur & dim images

### ISSUE THREAD

**Issue by yafp** [BigE/desk-changer#22]
the idea is influenced by muzei (https://play.google.com/store/apps/details?id=net.nurik.roman.muzei&hl=de)

It would be lovely to have an option to auto-blur and/or auto-dim all images by a defined factor. This would offer an easy option to have nondistracting wallpapers based from normal images-folders.

**Comment by BigE** [comment]
Thanks for taking the time to suggest this! This might be possible... but it would require the daemon to do some actual image processing, among other things. See my comments in #13 about how the daemon simply manipulates the settings key for the background. With that said, I could add an extra module to the daemon that would do processing to the image, store it in a separate (temporary) location, and set the settings string to this temporary (processed) file instead of the real image file.

My drawback about this is, I don't really want to get into image processing in the daemon itself. This adds a lot of complexity that I'm not sure I want to inherit in the daemon. I haven't made up my mind yet, but I'll do some research over the weekend and see what it might take. Thanks for the great suggestion!

**Comment by yafp** [comment]
First of all - thanks for the reply and considering the idea. I can fully understand if you dont like the idea of adding image processing in your core daemon.

>  I haven't made up my mind yet, but I'll do some research over the weekend and see what it might take. 

Let me know how that worked out ;)
