### ISSUE TITLE
When merging desk-changer with the system menu, the icon is not shown

### ISSUE THREAD

**Issue by wangxa** [BigE/desk-changer#25]
In version 23, if the extension is merged with the system menu, the icon will not shown, see the attached image.

![2](https://cloud.githubusercontent.com/assets/1250269/26264855/3d0f19da-3cd6-11e7-8bad-92dd41708e4c.png)

**Comment by BigE** [comment]
This is actually by design. See #16 which was a request to remove the icon when the system integration option is enabled. I agreed, partially, with the behavior since it really has no purpose when the system integration is enabled. The partially is because it will still show a preview icon if that option is enabled as well, that way you don't have to open a menu to see the preview. This feature was added in [Version 21](https://github.com/BigE/desk-changer/releases/tag/version-21) Thanks!

**Comment by wangxa** [comment]
I am sorry I didn't go through all the description. Thank you for your reply.
