### ISSUE TITLE
Ubuntu 17.10 - Error message

### ISSUE THREAD

**Issue by janive** [BigE/desk-changer#33]
Hi,
I just install desk changer from the Gnome-Website. When I try to change a wallpaper with the extension, the following errormessage appears:

error: Desk Changer: Gio.DBusError: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.Shell.Extensions.DeskChanger.Daemon was not provided by any .service files

Any idea, how I can fix this?

I use Ubuntu 17.10 with wayland and the gnome-session (not the ubuntu-session). I also tried to use Xorg, but the behaviour is the same.

**Comment by BigE** [comment]
More than likely you're getting this error because the daemon itself is not started. It should automatically start when the extension is loaded. You should check your error logs to see if the daemon is reporting any errors or not. The default way on ubuntu is by using `journalctl`

I'm going to guess that the error you're having is because the daemon is not starting due to missing dependencies. Please check the [README.md](https://github.com/BigE/desk-changer/blob/master/README.md) for what is needed to run the daemon. On Ubuntu, you must make sure python and python gobject introspection is installed using `apt-get install python python-gi` and then the daemon should start working.

**Comment by janive** [comment]
Hi BigE,
python and python-gi were missing. I thougt python3 and python3-gi would be enough. After installing the missing packages, the daemon now starts and the extension works. 
Thanks for your help.

**Comment by BigE** [comment]
I will have to look into this because the daemon should run on python3 just fine. I'll leave the ticket closed for now, but once I do a little more investigation, I'll see if there's something hindering it from working with python3. By default it runs using `#!/usr/bin/env python` so maybe when python3 is installed `python` itself doesn't exist? I'll find out! Thanks for the information!
