### ISSUE TITLE
Change interval to 0

### ISSUE THREAD

**Issue by seifane** [BigE/desk-changer#50]
When I change the interval to 0 the whole Gnome env stops responding and rebooting doesn't fix the problem. Maybe it shouldn't allow this change.

**Comment by BigE** [comment]
Yes, that's a great initial spot. I need to check here though https://github.com/BigE/desk-changer/blob/master/desk-changer%40eric.gach.gmail.com/schemas/org.gnome.shell.extensions.desk-changer.gschema.xml#L50 and see if there is a way to provide a min/max value here as well. It will be a multi-prong fix for sure.

**Comment by BigE** [comment]
https://gitlab.gnome.org/GNOME/glib/blob/master/gio/gschema.dtd for reference later. Would like to add <range> to the schema plus add code fixes to prevent this.

**Comment by seifane** [comment]
A day sounds good to me. Plenty enough and even better if you add more options :+1:

**Comment by BigE** [comment]
Yes, the settings are stored in dconf. This is managed by gsettings. You can try running the gsettings command without the extension installed to reset it
`gsettings set org.gnome.shell.extensions.desk-changer interval 500`
If this doesn't work because of a missing schema, you will need to manually install the extension. Grab a zip file from here and extract it to your extensions folder, then run the command, specifying where the schema is
`gsettings --schemadir=~/.local/share/gnome-shell/extensions/desk-changer@eric.gach.gmail.com/schemas/ set org.gnome.shell.extensions.desk-changer interval 500`
This will just reset it back to the default value. You should be able to then use the extension again, so long as you don't try to set the interval to 0 again :stuck_out_tongue_winking_eye:

**Comment by seifane** [comment]
Oh glad I didn't try again :) I suspected it was stored elsewhere and since I'm not familiar with gsettings I thought I'd better asked. Don't worry I won't set it again to 0 although I might just try some negative numbers :rofl:

**Comment by BigE** [comment]
I've fixed the issue, I believe. I haven't tested yet, but if you want to pull the latest master branch and give it a try, you should be able to run it without changing anything else. I've updated the settings, the daemon, and the settings schema as seen [here](https://github.com/BigE/desk-changer/commit/3e9d50861ca9981219f18879cc9669b901039ea3) I'll close this out once I've made sure it's fixed and a release is made. Thanks again for the report!

**Comment by seifane** [comment]
I believe there's a small error in the if condition I've commented on the commit ! [Here](https://github.com/BigE/desk-changer/commit/3e9d50861ca9981219f18879cc9669b901039ea3#diff-c1793caafc3b7c105a468157f3e634b0R98)

**Comment by BigE** [comment]
hah, what an amazing typo. I will fix. thanks!

**Comment by BigE** [comment]
This should be fixed with [Version 31](https://github.com/BigE/desk-changer/releases/tag/version-31)
