### ISSUE TITLE
Gdm login screen background

### ISSUE THREAD

**Issue by fishnchips2** [BigE/desk-changer#53]
Would it be possible to change the login screen background as well as the screensaver? There's no gnome flag for it but the setting is in /usr/share/gnome-shell/theme/gdm3.css on my system (It's a symlink to /etc/alternatives/gdm3.css). The default setting is 

> #lockDialogGroup {
>   background: #2c001e url(resource:///org/gnome/shell/theme/noise-texture.png);
>   background-repeat: repeat; }

**Comment by BigE** [comment]
Unfortunately, this is outside of the scope of this extension. Since it only runs while the user is logged in, there would be nothing running to change it while you're sitting at the login screen. The daemon could run at the system level... but that would probably take a level of integration I'm just not wanting to support now. Thanks for the suggestion!

**Comment by fishnchips2** [comment]
Thanks for the prompt answer!
