### ISSUE TITLE
Multiple monitor support

### ISSUE THREAD

**Issue by dmzkrsk** [BigE/desk-changer#7]
Is it possible to have different wallpapers per monitor?

**Comment by BigE** [comment]
I've thought about this myself before, but the problem I have each time is with gnome itself. Someone please correct me if I'm wrong, but, the way I understand that gnome works is by displaying the current background image on each active display, leaving no way to set an image per-display, or stitch together an image large enough to stretch across displays. I would love to somehow work this feature in... so I'm leaving this open until I do more discovery. However, at this point, I just don't see it as possible just because of the way gnome itself works.

**Comment by BigE** [comment]
Closing this as I've not yet found a way to do something like this. Thanks again for the suggestion, unfortunately Gnome itself just doesn't make this easy.
