### ISSUE TITLE
ReferenceError: globalThis is not defined

### ISSUE THREAD

**Issue by tripkin** [BigE/desk-changer#82]
Whenever I try to activate this, it shows ERROR in the plugin status. If I go to settings, I get this:

ReferenceError: globalThis is not defined

Stack trace:
  @/home/username/.local/share/gnome-shell/extensions/desk-changer@eric.gach.gmail.com/_deskchanger.js:10:1
  @/home/username/.local/share/gnome-shell/extensions/desk-changer@eric.gach.gmail.com/prefs.js:10:1
  _getExtensionPrefsModule@resource:///org/gnome/shell/extensionPrefs/main.js:67:13
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  _selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:82:31
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  _onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:235:17
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  main@resource:///org/gnome/shell/extensionPrefs/main.js:389:5
  @<main>:1:43

I am running:
Debian 10.10 with gnome-shell 3.30.2

It has been this way for over a year now, even with previous versions of Debian 10. Any ideas on what would/could be causing this?

**Comment by BigE** [comment]
Hi @tripkin 

I think I might have a solution for that error in the develop branch. GJS updated their internals to use `globalThis` instead of `window`, but I think that was only for the gnome 40 release. I've updated this to detect if `globalThis` is defined or not. Please let me know if this fixes things for you.

Thanks for the report!

**Comment by tripkin** [comment]
Thanks, I will give it a try and let you know!

**Comment by tripkin** [comment]
I was unable to a git clone, I got the error:

> git clone -b develop git@github.com:BigE/desk-changer.git
> Cloning into 'desk-changer'...
> git@github.com: Permission denied (publickey).
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists.
> 

So I downloaded the zip, extracted it, changed into the main directory and ran Make, and got the following error,

> $ make all
> glib-compile-resources --sourcedir=./desk-changer@eric.gach.gmail.com/resources ./desk-changer@eric.gach.gmail.com/resources/org.gnome.Shell.Extensions.DeskChanger.gresource.xml
> make: glib-compile-resources: Command not found
> make: *** [Makefile:13: compile-resources] Error 127

also as sudo. I verified that I have gjs >= 1.54

> apt policy gjs
> gjs:
>   Installed: 1.54.3-1

My understanding is that glib-compile-schemas and glib-compile-resources are part of libglib2.0-bin, which is also installed:

> apt policy libglib2.0-bin 
> libglib2.0-bin:
>   Installed: 2.58.3-2+deb10u3
> 

Any ideas on what I am doing wrong?

**Comment by BigE** [comment]
Hi @tripkin,

The first error can be resolved by using the https version, instead of ssh. You can find the URL to clone here https://github.com/BigE/desk-changer.git which should work just the same. If you would still rather use the SSH version, you would just need to register your SSH key with a github account to make it work. 

It looks like in Debian testing (which I'm guessing you're running with glib 2.58 installed) the package that contains the glib-compile-schemas command has changed to libglib2.0-bin-dev. See if installing that doesn't make that compile command work for you?

Thanks for your feedback so far!

**Comment by BigE** [comment]
Just an update. This extension only supports gnome 3.30 up to version 27 of the plugin. It was a mistake for me to include it in the metadata.json above that version, which I've [corrected](https://github.com/BigE/desk-changer/commit/01f9aaca3076937e9f29082caf41af3a91a0f610) now.

Thanks!
