### ISSUE TITLE
Show Icon as Preview Not Working

### ISSUE THREAD

**Issue by curvatura99** [BigE/desk-changer#86]
When first loading the extension on login to the desktop if you have the "Show Icon as Preview" option enabled the settings is ignored. However if you disable and re-enable the extension the icon preview appears. This started with the most recent update and occurs on Ubuntu 20.04 and 20.10.

**Comment by BigE** [comment]
Thanks for the report @curvatura99! 

I can confirm this is happening and I think I know why already. I'll have to figure out exactly how to fix it, but it looks like when the extension is first loaded, the daemon might not have a preview available. It should receive the daemon preview signal and updating accordingly.. I'm just not sure if I missed this or not.

**Comment by curvatura99** [comment]
Thank you the quick response. It's not a show stopper, so whenever you have time is good..

**Comment by curvatura99** [comment]
Thank you for the quick response. It's not a show stopper, so whenever you have time.

**Comment by BigE** [comment]
@curvatura99 no worries! I took a quick swing at it yesterday while I had some spare time... it wasn't a quick problem 😅 The problem comes because the signal from the daemon is ONLY attached when we receive a valid wallpaper preview. During start up, it doesn't receive one so the signal is never attached, even if the setting is to show a preview. I'll just need to replace where that signal is attached to fix it. It'll take a small refactor of the code that controls the icon, but it shouldn't take long!

Thanks again for the report. I'll get to this eventually!

**Comment by BigE** [comment]
This is updated, but only in the [latest release](https://github.com/BigE/desk-changer/releases/tag/version-36) which is only compatible with Gnome 45.
