### ISSUE TITLE
Different wallpaper for each monitor

### ISSUE THREAD

**Issue by CCaroV** [BigE/desk-changer#90]
Hi!

Do you think is possible to get a different wallpaper on a multi-monitor setup?

**Comment by BigE** [comment]
No and this is purely due to the limitations of Gnome and how it works. I'm simply changing a setting in gnome and it changes the background. If they update in the future to have multi-monitor support, I will gladly adapt that into the extension.

I won't say it's impossible, because it could be done by stitching together images into one large image before changing the background key in the settings, and then updating the key to the resulting image instead. I just have no plans of adding support like this to the extension myself.
