### ISSUE TITLE
desk-changer freeze

### ISSUE THREAD

**Issue by Netmage-76** [BigE/desk-changer#92]
Hello,

desk-changer window freeze in Ubuntu 22.04 (it tested it with 5 clients) as soon as someone click at "Add Folders" and the gnome file browser opens. The installation was done with the gnome extension manager.

Ubuntu 20.04 works without any problem.

**Comment by CIAMagnet** [comment]
Same issue here on Fedora 36 with GNOME 42 on both Wayland and X11 sessions.

**Comment by kirmaha** [comment]
Same here, and it happens too when I try to add a File. Removing or checking/unchecking works.
I installed the extension with Extension Manager flatpak on Ubuntu 22.04 LTS (I tried to set it up through Extensions flatpak, without reinstalling, and the same bug occurs).

I can close the two frozen settings windows hitting Escape twice.

**Comment by nickurak** [comment]
It's not exactly a freeze, but it's ODD.

The focus remains stuck on the main settings window, even while the (presumably modal) file/folder selector is open.

You can go back and interact with the main settings window.

What's really weird is the workaround: Once the main settings window is CLOSED, the regular behavior for the file dialogs seems to resume, and you can actually add folders/files correctly!

**Comment by BigE** [comment]
Hi all, this should be fixed with my [latest commit](https://github.com/BigE/desk-changer/commit/cf7f8ff0d79b913e53b27f9bbf737752c78679bf) to develop, as I didn't correctly set the dialog parent. I'll be pushing a release out soon-ish, I'm just making sure there are no other issues like this outstanding. Thank you all for reporting!
